fichas = [
    {"dato": "Country", "texto": "Panama (PAN)"},
    {"dato": "Long Name", "texto": "Republic of Panama (PAN)"},
    {"dato": "Income Group", "texto": "High income"},
    {"dato": "Region", "texto": "Latin America & Caribbean"},
    {"dato": "Lending category", "texto": "IBRD"},
    {"dato": "Currency Unit", "texto": "Panamanian balboa"},
    {"dato": "Latest population census", "texto": "2020 (expected)"},
    {"dato": "Latest household survey", "texto": "Multiple Indicator Cluster Survey, 2013"},
    {"dato": "National accounts base year", "texto": "Original chained constant price data are rescaled."},
    {"dato": "National accounts reference year", "texto": "2007"},
    {"dato": "System of National Accounts", "texto": "Country uses the 1993 System of National Accounts methodology"},
    {"dato": "SNA price valuation", "texto": "Value added at basic prices (VAB)"},
    {"dato": "PPP survey years", "texto": "2017, 2011"},
    {"dato": "Balance of Payments Manual in use", "texto": "BPM6"},
    {"dato": "System of trade", "texto": "Special trade system"},
    {"dato": "IMF data dissemination standard", "texto": "Enhanced General Data Dissemination System (e-GDDS)"},
    {"dato": "Source of most recent Income and expenditure data", "texto": "Integrated household survey (IHS), 2016"},
    {"dato": "Vital registration complete", "texto": "Yes"},
    {"dato": "Latest agricultural census", "texto": "2011"},
    {"dato": "Latest industrial data", "texto": "2001"},
    {"dato": "Latest trade data", "texto": "2016"},
    {"dato": "2-alpha code", "texto": "PA"},
    {"dato": "WB-2 code", "texto": "PA"},
    {"dato": "Table Name", "texto": "Panama"},
    {"dato": "Short Name", "texto": "Panama"},
    {"dato": "Country Name","texto": "Panama"},
    {"dato": "Country Code","texto": "PAN"},
    {"dato": "Indicator Name","texto": "Immunization, measles (% of children ages 12-23 months)"},
    {"dato": "Indicator Code","texto": "SH.IMM.MEAS"},
    {"dato": "1960","texto": "No Reportado"},
    {"dato": "1961","texto": "No Reportado"},
    {"dato": "1962","texto": "No Reportado"},
    {"dato": "1963","texto": "No Reportado"},
    {"dato": "1964","texto": "No Reportado"},
    {"dato": "1965","texto": "No Reportado"},
    {"dato": "1966","texto": "No Reportado"},
    {"dato": "1967","texto": "No Reportado"},
    {"dato": "1968","texto": "No Reportado"},
    {"dato": "1969","texto": "No Reportado"},
    {"dato": "1970","texto": "No Reportado"},
    {"dato": "1971","texto": "No Reportado"},
    {"dato": "1972","texto": "No Reportado"},
    {"dato": "1973","texto": "No Reportado"},
    {"dato": "1974","texto": "No Reportado"},
    {"dato": "1975","texto": "No Reportado"},
    {"dato": "1976","texto": "No Reportado"},
    {"dato": "1977","texto": "No Reportado"},
    {"dato": "1978","texto": "No Reportado"},
    {"dato": "1979","texto": "No Reportado"},
    {"dato": "1980","texto": "71"},
    {"dato": "1981","texto": "76"},
    {"dato": "1982","texto": "64"},
    {"dato": "1983","texto": "85"},
    {"dato": "1984","texto": "72"},
    {"dato": "1985","texto": "84"},
    {"dato": "1986","texto": "74"},
    {"dato": "1987","texto": "78"},
    {"dato": "1988","texto": "73"},
    {"dato": "1989","texto": "73"},
    {"dato": "1990","texto": "73"},
    {"dato": "1991","texto": "80"},
    {"dato": "1992","texto": "76"},
    {"dato": "1993","texto": "83"},
    {"dato": "1994","texto": "84"},
    {"dato": "1995","texto": "84"},
    {"dato": "1996","texto": "90"},
    {"dato": "1997","texto": "92"},
    {"dato": "1998","texto": "96"},
    {"dato": "1999","texto": "90"},
    {"dato": "2000","texto": "97"},
    {"dato": "2001","texto": "95"},
    {"dato": "2002","texto": "95"},
    {"dato": "2003","texto": "95"},
    {"dato": "2004","texto": "97"},
    {"dato": "2005","texto": "99"},
    {"dato": "2006","texto": "95"},
    {"dato": "2007","texto": "95"},
    {"dato": "2008","texto": "96"},
    {"dato": "2009","texto": "96"},
    {"dato": "2010","texto": "97"},
    {"dato": "2011","texto": "97"},
    {"dato": "2012","texto": "98"},
    {"dato": "2013","texto": "92"},
    {"dato": "2014","texto": "90"},
    {"dato": "2015","texto": "93"},
    {"dato": "2016","texto": "95"},
    {"dato": "2017","texto": "98"},
    {"dato": "2018","texto": "98"},
    {"dato": "2019","texto": "97"},
    {"dato": "2020","texto": "No Reportado"},
    {"dato": "2021","texto": "No Reportado"}
]